apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopping-cart-ingress
  namespace: dev
spec:
  ingressClassName: nginx
  rules:
  - host: shopping.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shopping-cart-svc
            port:
              number: 80
