apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-svc
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: shopping-cart
  ports:
  - name : metrics
    port: 80
    targetPort: 8070
