apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart
  namespace: dev
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: shopping-cart
  template:
    metadata:
      labels:
        app: shopping-cart
    spec:
      containers:
      - name: shopping-cart
        image: binay8025/binayp:dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8070

        envFrom:
        - configMapRef:
            name: shopping-cart-config
        - secretRef:
            name: shopping-cart-secret

        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"

